In [8]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris=datasets.load_iris()
X=iris.data
y=iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy*100:.2f}%")

Accuracy:100.00%


In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.datasets import load_iris

In [16]:
x,y=load_iris(return_X_y=True)

In [17]:
pd.DataFrame(X)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40)

In [20]:
classifier=GaussianNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [21]:
result=confusion_matrix(y_test,y_pred)
print("confusion_matrix")
print(result)

confusion_matrix
[[22  0  0]
 [ 0 15  4]
 [ 0  1 18]]


In [23]:
result2=classification_report(y_test,y_pred)
print("classification_report")
print(result2)

classification_report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.94      0.79      0.86        19
           2       0.82      0.95      0.88        19

    accuracy                           0.92        60
   macro avg       0.92      0.91      0.91        60
weighted avg       0.92      0.92      0.92        60



In [24]:
result3=accuracy_score(y_test,y_pred)
print("accuracy")
print(result3)

accuracy
0.9166666666666666
